  <script src="<?php base_url() ;?>assets/admin/vendor/jquery/dist/jquery.min.js"></script>
  <script src="<?php base_url() ;?>assets/admin/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="<?php base_url() ;?>assets/admin/vendor/js-cookie/js.cookie.js"></script>
  <script src="<?php base_url() ;?>assets/admin/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
  <script src="<?php base_url() ;?>assets/admin/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>
  <!-- Optional JS -->
  <script src="<?php base_url() ;?>assets/admin/vendor/chart.js/dist/Chart.min.js"></script>
  <script src="<?php base_url() ;?>assets/admin/vendor/chart.js/dist/Chart.extension.js"></script>
  <!-- Argon JS -->
  <script src="<?php base_url() ;?>assets/admin/js/argon.js?v=1.2.0"></script>